# Generated by Django 5.2.12 on 2026-03-29 09:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="11位手机号码",
                        max_length=11,
                        verbose_name="手机号码",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="用户头像图片",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户信息",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, verbose_name="姓名"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "男"), ("female", "女"), ("other", "其他")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="年龄"),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "高中"),
                            ("college", "大专"),
                            ("bachelor", "本科"),
                            ("master", "硕士"),
                            ("doctor", "博士"),
                        ],
                        max_length=20,
                        verbose_name="学历",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="毕业院校"
                    ),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "expected_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="期望职位"
                    ),
                ),
                (
                    "expected_salary_min",
                    models.IntegerField(
                        blank=True,
                        help_text="单位：元/月",
                        null=True,
                        verbose_name="期望薪资下限",
                    ),
                ),
                (
                    "expected_salary_max",
                    models.IntegerField(
                        blank=True,
                        help_text="单位：元/月",
                        null=True,
                        verbose_name="期望薪资上限",
                    ),
                ),
                (
                    "expected_cities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="期望工作的城市列表",
                        verbose_name="期望城市",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fulltime", "全职"),
                            ("parttime", "兼职"),
                            ("intern", "实习"),
                            ("remote", "远程"),
                        ],
                        default="fulltime",
                        max_length=20,
                        verbose_name="工作性质",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="技能列表，包含名称、水平、年限",
                        verbose_name="技能标签",
                    ),
                ),
                (
                    "work_experience",
                    models.IntegerField(
                        default=0, help_text="工作年数", verbose_name="工作年限"
                    ),
                ),
                (
                    "experience_detail",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="工作经历详情列表",
                        verbose_name="工作经历",
                    ),
                ),
                ("resume_url", models.URLField(blank=True, verbose_name="简历链接")),
                ("introduction", models.TextField(blank=True, verbose_name="自我介绍")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户画像",
                "verbose_name_plural": "用户画像",
                "db_table": "user_profiles",
            },
        ),
    ]
