# Generated by Django 5.2.12 on 2026-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user_id"], name="profile_user_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["education"], name="profile_education_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["work_experience"], name="profile_experience_idx"
            ),
        ),
    ]
