# Generated by Django 5.2.12 on 2026-03-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserJobInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "浏览"),
                            ("favorite", "收藏"),
                            ("unfavorite", "取消收藏"),
                            ("apply", "投递"),
                            ("rating", "评分"),
                        ],
                        max_length=20,
                        verbose_name="交互类型",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="1-5分，分数越高表示越满意",
                        null=True,
                        verbose_name="评分",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        help_text="浏览时长，单位：秒",
                        null=True,
                        verbose_name="浏览时长",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="如：推荐、搜索、首页等",
                        max_length=50,
                        verbose_name="来源",
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        help_text="如：PC、Mobile、App",
                        max_length=50,
                        verbose_name="设备",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用户交互记录",
                "verbose_name_plural": "用户交互记录",
                "db_table": "user_job_interactions",
            },
        ),
        migrations.CreateModel(
            name="UserSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity",
                    models.FloatField(
                        help_text="余弦相似度，范围-1到1", verbose_name="相似度"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="计算时间"),
                ),
            ],
            options={
                "verbose_name": "用户相似度",
                "verbose_name_plural": "用户相似度",
                "db_table": "user_similarities",
            },
        ),
        migrations.CreateModel(
            name="JobSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity",
                    models.FloatField(
                        help_text="相似度，范围0到1", verbose_name="相似度"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="计算时间"),
                ),
                (
                    "job1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_job1",
                        to="jobs.job",
                        verbose_name="职位1",
                    ),
                ),
                (
                    "job2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_job2",
                        to="jobs.job",
                        verbose_name="职位2",
                    ),
                ),
            ],
            options={
                "verbose_name": "职位相似度",
                "verbose_name_plural": "职位相似度",
                "db_table": "job_similarities",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="推荐算法计算的分数，范围0-1", verbose_name="推荐分数"
                    ),
                ),
                (
                    "reasons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="推荐的详细理由列表",
                        verbose_name="推荐理由",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("user_cf", "User-based协同过滤"),
                            ("item_cf", "Item-based协同过滤"),
                            ("hybrid", "混合推荐"),
                            ("cold_start", "冷启动推荐"),
                            ("content", "基于内容推荐"),
                        ],
                        max_length=50,
                        verbose_name="推荐算法",
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(default=False, verbose_name="是否已查看"),
                ),
                (
                    "is_interacted",
                    models.BooleanField(default=False, verbose_name="是否已交互"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_to",
                        to="jobs.job",
                        verbose_name="推荐职位",
                    ),
                ),
            ],
            options={
                "verbose_name": "推荐结果",
                "verbose_name_plural": "推荐结果缓存",
                "db_table": "recommendations",
            },
        ),
    ]
