# Generated by Django 5.2.12 on 2026-03-29 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="userjobinteraction",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="jobs.job",
                verbose_name="职位",
            ),
        ),
        migrations.AddField(
            model_name="userjobinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="usersimilarity",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="similarities_as_user1",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户1",
            ),
        ),
        migrations.AddField(
            model_name="usersimilarity",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="similarities_as_user2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户2",
            ),
        ),
        migrations.AddIndex(
            model_name="jobsimilarity",
            index=models.Index(
                fields=["job1", "-similarity"], name="job_similar_job1_id_8dcf85_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobsimilarity",
            unique_together={("job1", "job2")},
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "-score"], name="recommendat_user_id_8236a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "algorithm"], name="recommendat_user_id_d27c23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["created_at"], name="recommendat_created_02802f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recommendation",
            unique_together={("user", "job", "created_at")},
        ),
        migrations.AddIndex(
            model_name="userjobinteraction",
            index=models.Index(
                fields=["user", "job"], name="user_job_in_user_id_31bba4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userjobinteraction",
            index=models.Index(
                fields=["user", "interaction_type"],
                name="user_job_in_user_id_3f2c0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userjobinteraction",
            index=models.Index(
                fields=["job", "interaction_type"], name="user_job_in_job_id_db933b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userjobinteraction",
            index=models.Index(
                fields=["created_at"], name="user_job_in_created_7de4ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersimilarity",
            index=models.Index(
                fields=["user1", "-similarity"], name="user_simila_user1_i_83b897_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usersimilarity",
            unique_together={("user1", "user2")},
        ),
    ]
