# Generated by Django 5.2.12 on 2026-03-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="公司名称"
                    ),
                ),
                ("logo", models.URLField(blank=True, verbose_name="公司Logo")),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0-20", "0-20人"),
                            ("20-99", "20-99人"),
                            ("100-499", "100-499人"),
                            ("500-999", "500-999人"),
                            ("1000-9999", "1000-9999人"),
                            ("10000+", "10000人以上"),
                        ],
                        max_length=20,
                        verbose_name="公司规模",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="所属行业"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="公司简介")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="公司地址"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="公司官网")),
                (
                    "financing_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unfinanced", "未融资"),
                            ("angel", "天使轮"),
                            ("a", "A轮"),
                            ("b", "B轮"),
                            ("c", "C轮"),
                            ("d", "D轮及以上"),
                            ("listed", "已上市"),
                            ("acquired", "被收购"),
                        ],
                        max_length=20,
                        verbose_name="融资阶段",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "公司",
                "verbose_name_plural": "公司信息",
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="JobTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("skill", "技术栈"),
                            ("benefit", "福利待遇"),
                            ("industry", "行业"),
                            ("other", "其他"),
                        ],
                        default="skill",
                        max_length=20,
                        verbose_name="标签分类",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#409EFF",
                        help_text="十六进制颜色代码",
                        max_length=20,
                        verbose_name="标签颜色",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "职位标签",
                "verbose_name_plural": "职位标签",
                "db_table": "job_tags",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="jobs.jobcategory",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "职位分类",
                "verbose_name_plural": "职位分类",
                "db_table": "job_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="如：高级Python开发工程师",
                        max_length=200,
                        verbose_name="职位标题",
                    ),
                ),
                (
                    "salary_min",
                    models.IntegerField(
                        help_text="单位：元/月", verbose_name="最低薪资"
                    ),
                ),
                (
                    "salary_max",
                    models.IntegerField(
                        help_text="单位：元/月", verbose_name="最高薪资"
                    ),
                ),
                (
                    "salary_note",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="薪资说明"
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="工作地点")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="详细地址"
                    ),
                ),
                (
                    "education_required",
                    models.CharField(
                        choices=[
                            ("unlimited", "不限"),
                            ("high_school", "高中"),
                            ("college", "大专"),
                            ("bachelor", "本科"),
                            ("master", "硕士"),
                            ("doctor", "博士"),
                        ],
                        default="unlimited",
                        max_length=20,
                        verbose_name="学历要求",
                    ),
                ),
                (
                    "experience_required",
                    models.CharField(
                        choices=[
                            ("unlimited", "不限"),
                            ("0-1", "应届生/0-1年"),
                            ("1-3", "1-3年"),
                            ("3-5", "3-5年"),
                            ("5-10", "5-10年"),
                            ("10+", "10年以上"),
                        ],
                        default="unlimited",
                        max_length=20,
                        verbose_name="经验要求",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="职位的详细描述", verbose_name="职位描述"
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True, help_text="对候选人的要求", verbose_name="任职要求"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="紧急招聘"),
                ),
                ("is_hot", models.BooleanField(default=False, verbose_name="热门职位")),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览次数")),
                (
                    "apply_count",
                    models.IntegerField(default=0, verbose_name="投递次数"),
                ),
                (
                    "favorite_count",
                    models.IntegerField(default=0, verbose_name="收藏次数"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.company",
                        verbose_name="所属公司",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="jobs.jobcategory",
                        verbose_name="职位分类",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="jobs",
                        to="jobs.jobtag",
                        verbose_name="职位标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "职位",
                "verbose_name_plural": "职位信息",
                "db_table": "jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
