# Generated by Django 5.2.12 on 2026-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active", "-created_at"], name="job_active_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["location"], name="job_location_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["salary_min", "salary_max"], name="job_salary_range_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["education_required"], name="job_education_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["experience_required"], name="job_experience_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_hot", "is_active"], name="job_hot_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_urgent", "is_active"], name="job_urgent_active_idx"
            ),
        ),
    ]
